//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bookstoreEntities : DbContext
    {
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Thay thế UnintentionalCodeFirstException bằng cấu hình cascade delete
            modelBuilder.Entity<Sach>()
                        .HasRequired(e => e.maSach)  // Liên kết với thực thể Sach
                        .WithMany()                // Nếu nhiều đối tượng liên quan
                        .HasForeignKey(e => e.maTheLoai) // Khóa ngoại
                        .WillCascadeOnDelete(true);  // Kích hoạt xóa tự động

            base.OnModelCreating(modelBuilder);
        }

        public bookstoreEntities()
            : base("name=bookstoreEntities")

        {
        }
    
       
    
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<NoiDungSach> NoiDungSach { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<Sach> Sach { get; set; }
        public virtual DbSet<TheLoaiCon> TheLoaiCon { get; set; }
        public virtual DbSet<TheLoaiGoc> TheLoaiGoc { get; set; }
    }
}
