//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public string maSach { get; set; }
        public string tenSach { get; set; }
        public string tacGia { get; set; }
        public string maTheLoai { get; set; }
        public string hinhThucBia { get; set; }
        public Nullable<int> soTrang { get; set; }
        public Nullable<decimal> giaSach { get; set; }
        public string nhaXuatBan { get; set; }
        public string ngayXuatBan { get; set; }
        public Nullable<int> khuyenMai { get; set; }
        public string tenAnh { get; set; }
    
        public virtual NoiDungSach NoiDungSach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual TheLoaiCon TheLoaiCon { get; set; }
        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }
    }
}
