//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheLoaiGoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheLoaiGoc()
        {
            this.TheLoaiCon = new HashSet<TheLoaiCon>();
        }
    
        public string maTheLoai { get; set; }
        public string tenTheLoaiGoc { get; set; }
        public string tenAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheLoaiCon> TheLoaiCon { get; set; }
    }
}
