//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheLoaiCon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheLoaiCon()
        {
            this.Sach = new HashSet<Sach>();
        }
    
        public string maTheLoaiCon { get; set; }
        public string tenTheLoaiCon { get; set; }
        public string maTheLoaiGoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach> Sach { get; set; }
        public virtual TheLoaiGoc TheLoaiGoc { get; set; }
    }
}
